# max line length
max_width = 120
#width_heuristics = {}
error_on_line_overflow = true
error_on_unformatted = true

# others
#fn_params_layout = "Compressed"
format_strings = true
match_block_trailing_comma = true
newline_style = "Unix"
normalize_doc_attributes = true
overflow_delimited_expr = true
use_field_init_shorthand = true
use_try_shorthand = true
version = "Two"
where_single_line = true
brace_style = "PreferSameLine"
wrap_comments = true
