name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install nightly
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly, stable
        override: true
        components: rustfmt, clippy
    - name: Format
      uses: actions-rs/cargo@v1
      with:
        toolchain: nightly
        command: fmt
        args: --all -- --check
    - name: Lint
      uses: actions-rs/cargo@v1
      with:
        toolchain: nightly
        command: clippy
        args: -- -D warnings
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        toolchain: nightly
        command: cargo
        args: +nightly build --verbose
    - name: Tests
      uses: actions-rs/cargo@v1
      with:
        toolchain: nightly
        command: cargo
        args: +nightly test --verbose
    - name: Build (Stable)
      uses: actions-rs/cargo@v1
      with:
        toolchain: stable
        command: cargo
        args: build --verbose
    - name: Tests (Stable)
      uses: actions-rs/cargo@v1
      with:
        toolchain: stable
        command: cargo
        args: test --verbose
    - name: Build (Release)
      uses: actions-rs/cargo@v1
      with:
        toolchain: nightly
        command: cargo
        args: build --release --verbose
    - name: Build (Stable, Release)
      uses: actions-rs/cargo@v1
      with:
        toolchain: stable
        command: cargo
        args: build --release --verbose
